version: "1.0"
info:
  scaffold: myStringLenghtEdgeFLService
  model: int-scaffold
services:
- serviceName: pub.string:length
  packages:
  - name: WmPublic
    version: 11.0.0.0.244
- serviceName: edge.rahs_bugbash.integrations:myStringLenghtEdgeFLService
  packages:
  - name: EdgeRAHS_Bugbash
    version: "1.0"
